# Generated by Django 3.0 on 2020-01-07 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradime', models.CharField(max_length=50)),
                ('lat', models.DecimalField(decimal_places=3, max_digits=5)),
                ('lon', models.DecimalField(decimal_places=3, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='CityData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temper', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vlaga', models.IntegerField(verbose_name=3)),
                ('tlak', models.DecimalField(decimal_places=1, max_digits=5)),
                ('tlaktend', models.DecimalField(decimal_places=1, max_digits=3)),
                ('vjetarsmjer', models.CharField(max_length=2)),
                ('vjetarbrzina', models.DecimalField(decimal_places=1, max_digits=3)),
                ('vrijeme', models.CharField(max_length=50)),
                ('datum', models.DateField(auto_now=True)),
                ('sat', models.IntegerField(verbose_name=2)),
                ('grad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.City')),
            ],
        ),
    ]
